name: lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: git config --global url."https://kapeta-bot:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: golangci-lint
        env:
          GOPRIVATE: github.com/kapetacom/*
        uses: golangci/golangci-lint-action@v3.7.0        
        with:
          args: --verbose --timeout=5m


